services:
  discovery-service:
    build: ./bank-account-ms-enset-bdcc-app/discovery-service
    container_name: ebank-discovery-service
    ports:
      - '8761:8761'
    expose:
      - '8761'
    healthcheck:
      #-f ça veux dire en cas d'echecs de la requete ça voir se retourne un code de l'etat dechecs
      test: [ "CMD", "curl", "-f", "http://localhost:8761/actuator/health" ]
      # Linterval ça veut dire que chaque 10 s il va envoi la requete(ping)
      interval: 10s
      retries: 4
  config-service:
    build: ./bank-account-ms-enset-bdcc-app/config-service
    container_name: config-service
    ports:
      - '9999:9999'
    expose:
      - '9999'
    environment:
      - DISCOVERY_SERVICE_URL=http://ebank-discovery-service:8761/eureka
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9999/actuator/health" ]
      interval: 10s
      retries: 4
    depends_on:
      discovery-service:
        condition: service_healthy
  customer-service:
    build: ./bank-account-ms-enset-bdcc-app/customer-service
    container_name: customer-service
    ports:
      - '8081:8081'
    expose:
      - '8081'
    environment:
      - DISCOVERY_SERVICE_URL=http://ebank-discovery-service:8761/eureka
      - CONFIG_SERVICE_URL=http://config-service:9999
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8081/actuator/health" ]
      interval: 10s
      retries: 4
    depends_on:
      config-service:
        condition: service_healthy
  account-service:
    build: ./bank-account-ms-enset-bdcc-app/account-service
    container_name: account-service
    ports:
      - '8082:8082'
    expose:
      - '8082'
    environment:
      - DISCOVERY_SERVICE_URL=http://ebank-discovery-service:8761/eureka
      - CONFIG_SERVICE_URL=http://config-service:9999
    depends_on:
      customer-service:
        condition: service_healthy
  gateway-service:
    build: ./bank-account-ms-enset-bdcc-app/gateway-service
    container_name: gateway-service
    ports:
      - '8888:8888'
    expose:
      - '8888'
    environment:
      - DISCOVERY_SERVICE_URL=http://ebank-discovery-service:8761/eureka
      - CONFIG_SERVICE_URL=http://config-service:9999
    depends_on:
      config-service:
        condition: service_healthy
  front-end-angular:
    build: ./angular-front-end
    container_name: front-send-angular
    ports:
      - '82:80'
    expose:
      - '82'